services:
  mtproxy-whitelist:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mtproxy-whitelist
    restart: unless-stopped
    
    # 端口映射 - 仅在bridge模式下使用
    # NAT模式下使用host网络时，此配置会被docker-compose忽略
    ports:
      - "${MTPROXY_PORT:-14202}:443"   # bridge模式：外部端口 -> nginx内部443端口
      - "${WEB_PORT:-8989}:8888"       # bridge模式：外部端口 -> nginx内部8888端口
    
    # 环境变量配置
    environment:
      - MTPROXY_DOMAIN=${MTPROXY_DOMAIN:-azure.microsoft.com}
      - MTPROXY_TAG=${MTPROXY_TAG:-}
      - SECRET_KEY=${SECRET_KEY:-ee004d64da8e145b8daa35a2012e220e}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS:-24}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - MTPROXY_PORT=${MTPROXY_PORT:-14202}     # MTProxy代理端口，nginx监听此端口
      - INTERNAL_MTPROXY_PORT=444               # MTProxy实际运行端口
      - WEB_PORT=${WEB_PORT:-8989}              # Web管理端口变量化
      - API_PORT=8080                           # API内部端口
      - NAT_MODE=${NAT_MODE:-true}              # NAT模式开关
      - NGINX_STREAM_PORT=${NGINX_STREAM_PORT:-14202}  # nginx stream 端口
      - NGINX_WEB_PORT=${NGINX_WEB_PORT:-8989}         # nginx web 端口
    
    # 数据卷挂载
    volumes:
      - mtproxy_data:/data
      - mtproxy_logs:/var/log
      - mtproxy_config:/opt/mtproxy
    
    # 网络配置 - 支持NAT模式动态切换
    network_mode: "${NETWORK_MODE:-bridge}"
    
    # 健康检查 (使用固定内部端口)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
    
    # 安全配置
    security_opt:
      - no-new-privileges:true
    
    # 临时文件系统挂载
    tmpfs:
      - /tmp:size=100M,noexec,nosuid,nodev
      - /var/run:size=100M,noexec,nosuid,nodev
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # 添加标签用于识别
    labels:
      - "traefik.enable=false"
      - "com.mtproxy.whitelist=true"
      - "com.mtproxy.version=4.0"
      - "com.mtproxy.whitelist.mapping=fixed"
      - "com.mtproxy.api.sync=enabled"
      - "com.mtproxy.reload.script=integrated"

# 数据卷定义
volumes:
  mtproxy_data:
    driver: local
  mtproxy_logs:
    driver: local  
  mtproxy_config:
    driver: local