services:
  mtproxy-whitelist:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mtproxy-whitelist
    restart: unless-stopped
    
    # Bridge模式：使用bridge网络 + 端口映射
    network_mode: bridge
    ports:
      - "${MTPROXY_PORT:-14202}:443"   # 外部端口 -> nginx内部443端口
      - "${WEB_PORT:-8989}:8888"       # 外部端口 -> nginx内部8888端口
    
    # 环境变量配置
    environment:
      - MTPROXY_DOMAIN=${MTPROXY_DOMAIN:-azure.microsoft.com}
      - MTPROXY_TAG=${MTPROXY_TAG:-}
      - SECRET_KEY=${SECRET_KEY:-ee004d64da8e145b8daa35a2012e220e}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS:-24}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - MTPROXY_PORT=${MTPROXY_PORT:-14202}     # 用于日志和配置
      - INTERNAL_MTPROXY_PORT=444               # MTProxy实际运行端口
      - WEB_PORT=${WEB_PORT:-8989}              # 用于日志和配置
      - API_PORT=8080                           # API内部端口
      - NAT_MODE=false                          # Bridge模式
      - NETWORK_MODE=bridge                     # Bridge网络
      - NGINX_STREAM_PORT=443                   # nginx固定监听443
      - NGINX_WEB_PORT=8888                     # nginx固定监听8888
    
    # 数据卷挂载
    volumes:
      - mtproxy_data:/data
      - mtproxy_logs:/var/log
      - mtproxy_config:/opt/mtproxy
    
    # Bridge模式健康检查 - 使用固定内部端口
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
    
    # 安全配置
    security_opt:
      - no-new-privileges:true
    
    # 临时文件系统挂载
    tmpfs:
      - /tmp:size=100M,noexec,nosuid,nodev
      - /var/run:size=100M,noexec,nosuid,nodev
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Bridge模式标签
    labels:
      - "com.mtproxy.mode=bridge"
      - "com.mtproxy.network=bridge"
      - "com.mtproxy.ports.mapping=${MTPROXY_PORT:-14202}:443,${WEB_PORT:-8989}:8888"

# 数据卷定义
volumes:
  mtproxy_data:
    driver: local
  mtproxy_logs:
    driver: local  
  mtproxy_config:
    driver: local