# NAT直连模式 Docker Compose 配置
# Nginx直接监听外部端口，无HAProxy层
# 适用于无需PROXY Protocol的NAT环境

services:
  mtproxy-whitelist:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mtproxy-whitelist
    restart: unless-stopped

    # NAT模式：使用host网络
    network_mode: host

    environment:
      - DEPLOYMENT_MODE=nat-direct                           # 部署模式：NAT直连
      - MTPROXY_DOMAIN=${MTPROXY_DOMAIN:-azure.microsoft.com}
      - MTPROXY_TAG=${MTPROXY_TAG:-}
      - SECRET_KEY=${SECRET_KEY:-ee004d64da8e145b8daa35a2012e220e}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS:-24}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}

      # 新端口变量标准
      - EXTERNAL_PROXY_PORT=${EXTERNAL_PROXY_PORT:-14202}         # 外部代理端口（Nginx直接监听）
      - EXTERNAL_WEB_PORT=${EXTERNAL_WEB_PORT:-8989}              # 外部Web端口（Nginx直接监听）
      - BACKEND_MTPROXY_PORT=${BACKEND_MTPROXY_PORT:-444}         # MTProxy后端端口
      - INTERNAL_API_PORT=${INTERNAL_API_PORT:-8080}              # API内部端口

      # 向后兼容的端口别名
      - MTPROXY_PORT=${EXTERNAL_PROXY_PORT:-14202}
      - WEB_PORT=${EXTERNAL_WEB_PORT:-8989}
      - INTERNAL_MTPROXY_PORT=${BACKEND_MTPROXY_PORT:-444}
      - API_PORT=${INTERNAL_API_PORT:-8080}

      # 遗留变量（向后兼容）
      - NAT_MODE=true
      - HAPROXY_ENABLED=false

    # 数据卷挂载
    volumes:
      - mtproxy_data:/data
      - mtproxy_logs:/var/log
      - mtproxy_config:/opt/mtproxy

    # 健康检查 - 使用新的多层次健康检查脚本
    healthcheck:
      test: ["CMD", "/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M

    # 安全配置
    security_opt:
      - no-new-privileges:true

    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # 添加标签用于识别
    labels:
      - "traefik.enable=false"
      - "com.mtproxy.whitelist=true"
      - "com.mtproxy.mode=nat-direct"

# 数据卷定义
volumes:
  mtproxy_data:
    driver: local
  mtproxy_logs:
    driver: local
  mtproxy_config:
    driver: local
